TARGET      := mineps2.elf
ENGINEDIR   := ../../engine

SRCDIR      := src
INCDIR      := inc
BUILDDIR    := obj
TARGETDIR   := bin
RESDIR      := res
SRCEXT      := cpp
VSMEXT      := vsm
VCLEXT      := vcl
VCLPPEXT    := vclpp
DEPEXT      := d
OBJEXT      := o

CFLAGS      :=
LIB         :=
LIBDIRS     :=
INC         := -I$(INCDIR)
INCDEP      := -I$(INCDIR)

include ../Makefile.tutorials-base
